name: DreamSpend
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
configs:
  Debug: debug
  Release: release
targets:
  DreamSpend:
    type: application
    platform: iOS
    sources:
      - path: DreamSpend/App
      - path: DreamSpend/Core
      - path: DreamSpend/Features
      - path: DreamSpend/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.teccod.DreamSpend
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: DreamSpend
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
  DreamSpendTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DreamSpend/Tests
    dependencies:
      - target: DreamSpend
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.evgeniy.DreamSpendTests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/DreamSpend.app/DreamSpend"
schemes:
  DreamSpend:
    build:
      targets:
        DreamSpend: all
        DreamSpendTests: [test]
    test:
      targets:
        - name: DreamSpendTests
      gatherCoverageData: true
